### ISSUE TITLE
.buckconfig options for libraries

### ISSUE THREAD

**Issue by isundaylee** [LoopPerfect/buckaroo#131]
As @njlr already raised in https://github.com/facebook/buck/issues/1458, `buck` currently doesn't use the root project `.buckconfig` for the cells (i.e. libraries, in our case). 

Would it be useful to implement a workaround, that merges the root .buckconfig into the libraries' upon checking out the libraries? For me, it would allow me to define custom flavors (`#debug`, `#release`, etc.) in my .buckconfig. 

I'm willing to contribute code if this is something that people think are useful.

**Comment by njlr** [comment]
I think this requires some more investigation. If I define a flavour in the top level config and build the top level with that flavour, do the dependencies also get built with that flavour?

If build flavours carry through cells then that would be a good solution for doing debug builds etc across and entire project.

**Comment by isundaylee** [comment]
Definitely correct me if I'm wrong, but I think currently what happens is that buck would try to build the libraries with that flavor, but seeing that the flavor doesn't exist in the library's `.buckconfig` file, would throw the following error (looks like a corner-case that is not anticipated by `buck`):

```
[-] PROCESSING BUCK FILES...FINISHED 0.8s [100%] 🏖  Watchman reported no changes
[-] DOWNLOADING... (0.00 B/S AVG, TOTAL: 0.00 B, 0 Artifacts)
[-] BUILDING...FINISHED 0.4s
[2017-08-18 23:51:21.499][error][command:null][tid:2197][com.facebook.buck.cli.Main] Uncaught exception at top level
com.google.common.util.concurrent.UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2214)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4053)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4057)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4986)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4992)
	at com.facebook.buck.cxx.CxxLibrary.getTransitiveCxxPreprocessorInput(CxxLibrary.java:168)
	at com.facebook.buck.cxx.CxxPreprocessables$1.visit(CxxPreprocessables.java:152)
	at com.facebook.buck.cxx.CxxPreprocessables$1.visit(CxxPreprocessables.java:147)
	at com.facebook.buck.graph.AbstractBreadthFirstThrowingTraversal.start(AbstractBreadthFirstThrowingTraversal.java:49)
	at com.facebook.buck.cxx.CxxPreprocessables.getTransitiveCxxPreprocessorInput(CxxPreprocessables.java:157)
	at com.facebook.buck.cxx.CxxPreprocessables.getTransitiveCxxPreprocessorInput(CxxPreprocessables.java:166)
	at com.facebook.buck.cxx.CxxDescriptionEnhancer.createBuildRulesForCxxBinary(CxxDescriptionEnhancer.java:844)
	at com.facebook.buck.cxx.CxxDescriptionEnhancer.createBuildRulesForCxxBinaryDescriptionArg(CxxDescriptionEnhancer.java:743)
	at com.facebook.buck.cxx.CxxBinaryDescription.createBuildRule(CxxBinaryDescription.java:214)
	at com.facebook.buck.cxx.CxxBinaryDescription.createBuildRule(CxxBinaryDescription.java:132)
	at com.facebook.buck.cxx.CxxBinaryDescription.createBuildRule(CxxBinaryDescription.java:51)
	at com.facebook.buck.rules.DefaultTargetNodeToBuildRuleTransformer.transform(DefaultTargetNodeToBuildRuleTransformer.java:68)
	at com.facebook.buck.rules.BuildRuleResolver.requireRule(BuildRuleResolver.java:133)
	at com.facebook.buck.rules.ActionGraphCache$1.visit(ActionGraphCache.java:174)
	at com.facebook.buck.rules.ActionGraphCache$1.visit(ActionGraphCache.java:169)
	at com.facebook.buck.graph.AbstractBottomUpTraversal.traverse(AbstractBottomUpTraversal.java:36)
	at com.facebook.buck.rules.ActionGraphCache.createActionGraph(ActionGraphCache.java:180)
	at com.facebook.buck.rules.ActionGraphCache.getActionGraph(ActionGraphCache.java:111)
	at com.facebook.buck.cli.BuildCommand.createActionGraphAndResolver(BuildCommand.java:814)
	at com.facebook.buck.cli.BuildCommand.createGraphs(BuildCommand.java:456)
	at com.facebook.buck.cli.BuildCommand.run(BuildCommand.java:414)
	at com.facebook.buck.cli.BuildCommand.runWithoutHelp(BuildCommand.java:381)
	at com.facebook.buck.cli.AbstractCommand.run(AbstractCommand.java:222)
	at com.facebook.buck.cli.AbstractContainerCommand.run(AbstractContainerCommand.java:66)
	at com.facebook.buck.cli.BuckCommand.run(BuckCommand.java:80)
	at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:900)
	at com.facebook.buck.cli.Main.runMainThenExit(Main.java:329)
	at com.facebook.buck.cli.Main.nailMain(Main.java:1674)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.martiansoftware.nailgun.NGSession.run(NGSession.java:338)
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2214)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4053)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4057)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4986)
	at com.facebook.buck.rules.BuildRuleResolver.requireMetadata(BuildRuleResolver.java:168)
	at com.facebook.buck.cxx.CxxLibraryDescription.queryMetadataCxxPreprocessorInput(CxxLibraryDescription.java:917)
	at com.facebook.buck.cxx.CxxLibrary.getCxxPreprocessorInput(CxxLibrary.java:148)
	at com.facebook.buck.cxx.CxxLibrary.getCxxPreprocessorInput(CxxLibrary.java:156)
	at com.facebook.buck.cxx.CxxPreprocessables$2.load(CxxPreprocessables.java:255)
	at com.facebook.buck.cxx.CxxPreprocessables$2.load(CxxPreprocessables.java:249)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3628)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2336)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2295)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2208)
	... 37 more
Caused by: java.lang.IllegalArgumentException
	at java.util.Optional.orElseThrow(Optional.java:290)
	at com.facebook.buck.cxx.CxxLibraryDescription.createMetadata(CxxLibraryDescription.java:962)
	at com.facebook.buck.cxx.CxxLibraryDescription.createMetadata(CxxLibraryDescription.java:71)
	at com.facebook.buck.rules.BuildRuleResolver$1.load(BuildRuleResolver.java:96)
	at com.facebook.buck.rules.BuildRuleResolver$1.load(BuildRuleResolver.java:79)
	at com.facebook.buck.rules.BuildRuleResolver$1.load(BuildRuleResolver.java:75)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3628)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2336)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2295)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2208)
	... 50 more
```

When I manually added the flavor into the libraries' `.buckconfig` files, the error went away and everything built as expected.

**Comment by njlr** [comment]
Interesting! I think we should put this to the buck team, since it is likely a bug.

On 19 Aug 2017, at 07:52, Jiahao Li <notifications@github.com<mailto:notifications@github.com>> wrote:


Definitely correct me if I'm wrong, but I think currently what happens is that buck would try to build the libraries with that flavor, but seeing that the flavor doesn't exist in the library's .buckconfig file, would throw the following error (looks like a corner-case that is not anticipated by buck):

[-] PROCESSING BUCK FILES...FINISHED 0.8s [100%] 🏖  Watchman reported no changes
[-] DOWNLOADING... (0.00 B/S AVG, TOTAL: 0.00 B, 0 Artifacts)
[-] BUILDING...FINISHED 0.4s
[2017-08-18 23:51:21.499][error][command:null][tid:2197][com.facebook.buck.cli.Main] Uncaught exception at top level
com.google.common.util.concurrent.UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2214)
        at com.google.common.cache.LocalCache.get(LocalCache.java:4053)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4057)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4986)
        at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4992)
        at com.facebook.buck.cxx.CxxLibrary.getTransitiveCxxPreprocessorInput(CxxLibrary.java:168)
        at com.facebook.buck.cxx.CxxPreprocessables$1.visit(CxxPreprocessables.java:152)
        at com.facebook.buck.cxx.CxxPreprocessables$1.visit(CxxPreprocessables.java:147)
        at com.facebook.buck.graph.AbstractBreadthFirstThrowingTraversal.start(AbstractBreadthFirstThrowingTraversal.java:49)
        at com.facebook.buck.cxx.CxxPreprocessables.getTransitiveCxxPreprocessorInput(CxxPreprocessables.java:157)
        at com.facebook.buck.cxx.CxxPreprocessables.getTransitiveCxxPreprocessorInput(CxxPreprocessables.java:166)
        at com.facebook.buck.cxx.CxxDescriptionEnhancer.createBuildRulesForCxxBinary(CxxDescriptionEnhancer.java:844)
        at com.facebook.buck.cxx.CxxDescriptionEnhancer.createBuildRulesForCxxBinaryDescriptionArg(CxxDescriptionEnhancer.java:743)
        at com.facebook.buck.cxx.CxxBinaryDescription.createBuildRule(CxxBinaryDescription.java:214)
        at com.facebook.buck.cxx.CxxBinaryDescription.createBuildRule(CxxBinaryDescription.java:132)
        at com.facebook.buck.cxx.CxxBinaryDescription.createBuildRule(CxxBinaryDescription.java:51)
        at com.facebook.buck.rules.DefaultTargetNodeToBuildRuleTransformer.transform(DefaultTargetNodeToBuildRuleTransformer.java:68)
        at com.facebook.buck.rules.BuildRuleResolver.requireRule(BuildRuleResolver.java:133)
        at com.facebook.buck.rules.ActionGraphCache$1.visit(ActionGraphCache.java:174)
        at com.facebook.buck.rules.ActionGraphCache$1.visit(ActionGraphCache.java:169)
        at com.facebook.buck.graph.AbstractBottomUpTraversal.traverse(AbstractBottomUpTraversal.java:36)
        at com.facebook.buck.rules.ActionGraphCache.createActionGraph(ActionGraphCache.java:180)
        at com.facebook.buck.rules.ActionGraphCache.getActionGraph(ActionGraphCache.java:111)
        at com.facebook.buck.cli.BuildCommand.createActionGraphAndResolver(BuildCommand.java:814)
        at com.facebook.buck.cli.BuildCommand.createGraphs(BuildCommand.java:456)
        at com.facebook.buck.cli.BuildCommand.run(BuildCommand.java:414)
        at com.facebook.buck.cli.BuildCommand.runWithoutHelp(BuildCommand.java:381)
        at com.facebook.buck.cli.AbstractCommand.run(AbstractCommand.java:222)
        at com.facebook.buck.cli.AbstractContainerCommand.run(AbstractContainerCommand.java:66)
        at com.facebook.buck.cli.BuckCommand.run(BuckCommand.java:80)
        at com.facebook.buck.cli.Main.runMainWithExitCode(Main.java:900)
        at com.facebook.buck.cli.Main.runMainThenExit(Main.java:329)
        at com.facebook.buck.cli.Main.nailMain(Main.java:1674)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.martiansoftware.nailgun.NGSession.run(NGSession.java:338)
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2214)
        at com.google.common.cache.LocalCache.get(LocalCache.java:4053)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4057)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4986)
        at com.facebook.buck.rules.BuildRuleResolver.requireMetadata(BuildRuleResolver.java:168)
        at com.facebook.buck.cxx.CxxLibraryDescription.queryMetadataCxxPreprocessorInput(CxxLibraryDescription.java:917)
        at com.facebook.buck.cxx.CxxLibrary.getCxxPreprocessorInput(CxxLibrary.java:148)
        at com.facebook.buck.cxx.CxxLibrary.getCxxPreprocessorInput(CxxLibrary.java:156)
        at com.facebook.buck.cxx.CxxPreprocessables$2.load(CxxPreprocessables.java:255)
        at com.facebook.buck.cxx.CxxPreprocessables$2.load(CxxPreprocessables.java:249)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3628)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2336)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2295)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2208)
        ... 37 more
Caused by: java.lang.IllegalArgumentException
        at java.util.Optional.orElseThrow(Optional.java:290)
        at com.facebook.buck.cxx.CxxLibraryDescription.createMetadata(CxxLibraryDescription.java:962)
        at com.facebook.buck.cxx.CxxLibraryDescription.createMetadata(CxxLibraryDescription.java:71)
        at com.facebook.buck.rules.BuildRuleResolver$1.load(BuildRuleResolver.java:96)
        at com.facebook.buck.rules.BuildRuleResolver$1.load(BuildRuleResolver.java:79)
        at com.facebook.buck.rules.BuildRuleResolver$1.load(BuildRuleResolver.java:75)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3628)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2336)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2295)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2208)
        ... 50 more


When I manually added the flavor into the libraries' .buckconfig files, the error went away and everything built as expected.

**Comment by njlr** [comment]
I have reported this issue to the Buck team: https://github.com/facebook/buck/issues/1469

**Comment by njlr** [comment]
Using "args" or "arg-files" you can set arbitrary flags inside arbitrary cells. This should serve as a solution to this issue (at least for now!) 

Details: https://github.com/facebook/buck/issues/1470#issuecomment-324059272
