### ISSUE TITLE
Fetching package boost-thread fails with System.Exception

### ISSUE THREAD

**Issue by fredy8** [LoopPerfect/buckaroo#329]
## Description
I was following the quickstart guide in the wiki. The commands I ran were:
buckaroo quickstart
buckaroo add github.com/buckaroo-pm/boost-thread

## Expected Behavior
I would expect boost-thread to be installed, but it's not installed in buckaroo/github/buckaroo-pm/

## Actual Behavior
When I run the command `buckaroo add github.com/buckaroo-pm/boost-thread`, after all dependencies for boost-thread are installed, I see the error message:

```
info No receipt found for buckaroo/github/buckaroo-pm/boost-thread; it will be installed.
info Installing buckaroo/github/buckaroo-pm/boost-thread...
System.Exception: Failed to fetch: https://github.com/buckaroo-pm/boost-thread.git 01e9e7a6c1afa9146b7cc9d059c33edbaa3cff07
   at <StartupCode$buckaroo>.$GitManager.FindCommit@118-5.Invoke(Boolean _arg9) in /Users/travis/build/LoopPerfect/buckaroo/buckaroo/GitManager.fs:line 119
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at Microsoft.FSharp.Control.AsyncPrimitives.unitAsync@607.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$buckaroo>.$GitCli.Buckaroo-IGit-HasCommit@105-2.Invoke(AsyncActivation`1 ctxt) in /Users/travis/build/LoopPerfect/buckaroo/buckaroo/GitCli.fs:line 105
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)
```

## Steps to Reproduce
1. buckaroo quickstart
2. buckaroo add github.com/buckaroo-pm/boost-thread

## Context
I was trying to install facebook/folly, which required boost-thread, but boost-thread failed. I then tried installing boost-thread individually, but it also failed.

## Your Environment
* Version used: v2.0.3
* Operating System and Architecture: macOS Sierra 10.12.6

**Comment by fredy8** [comment]
It seems to work if I specify the branch:

buckaroo add github.com/buckaroo-pm/boost-thread@branch=master

**Comment by nikhedonia** [comment]
Your log says:
`Failed to fetch: https://github.com/buckaroo-pm/boost-thread.git 01e9e7a6c1afa9146b7cc9d059c33edbaa3cff07`

This should definitely fail more gracefully, do a couple retries and print a good error message.

Additionally investigating your issue I stumbled on a small bug that would make things slower than it needs to be: https://github.com/LoopPerfect/buckaroo/pull/330 and should be merged soon

**Comment by njlr** [comment]
Closing this since https://github.com/LoopPerfect/buckaroo/pull/330 was merged.
