### ISSUE TITLE
Cannot start the quickstart tutorial

### ISSUE THREAD

**Issue by atifkarim** [LoopPerfect/buckaroo#377]
## Description
I am trying to initiate [Quickstart Project](https://buckaroo.readthedocs.io/en/latest/quickstart.html) but failed with the following Error message  
```
buckaroo: command not found
```
I have seen [this issue](https://github.com/LoopPerfect/buckaroo/issues/183) but could not solve my case. Maybe my approach is wrong and I am giving what I have done so far.

## Steps to Reproduce

The approaches i have followed so far:  
1. `mkdir my-project`
2. `cd my-project`
3. Then followed instructions [from here to install buck](https://github.com/LoopPerfect/buckaroo/wiki/Installation#linux-1)
    * `wget https://github.com/njlr/buck-warp/releases/download/v0.3.0/buck-2019.01.10.01-linux -O buck`
    * `chmod +x ./buck`
    * `./buck`
        * In this stage I have found a meesage  
`
This does not appear to be the root of a Buck project. Please 'cd'
to the root of your project before running buck. If this really is
the root of your project, run
'touch .buckconfig'
and then re-run your buck command.
Traceback (most recent call last):
  File "/net/users/Linux_Home/karim/.local/share/warp/packages/buck/bin/buck/programs/buck.py", line 241, in <module>
  File "/net/users/Linux_Home/karim/.local/share/warp/packages/buck/bin/buck/programs/buck.py", line 219, in main
  File "/net/users/Linux_Home/karim/.local/share/warp/packages/buck/bin/buck/programs/buck_project.py", line 149, in from_current_dir
    raise NoBuckConfigFoundException()
NoBuckConfigFoundException: This does not appear to be the root of a Buck project. Please 'cd'
to the root of your project before running buck. If this really is
the root of your project, run
'touch .buckconfig'
and then re-run your buck command.
`

        * So I have run `touch .buckconfig` and re-run `./buck` and I have seen `Description: Buck build tool` with some other info.

6. Then followed instructions [from here to install Buckaroo](https://github.com/LoopPerfect/buckaroo/wiki/Installation#linux)
    * `wget https://github.com/LoopPerfect/buckaroo/releases/download/v2.2.0/buckaroo-linux -O buckaroo`
    * `chmod +x ./buckaroo`
    * `./buckaroo`
    And the following text appeared which resembles that Buckaroo is installed properly(my assumption)
```
   ___           __                             
  / _ )__ ______/ /_____ ________  ___          
 / _  / // / __/  '_/ _ `/ __/ _ \/ _ \       
/____/\_,_/\__/_/\_\\_,_/_/  \___/\___/

Buck, Buck, Buckaroo! 🤠
https://buckaroo.pm
```
7. Then I have run [from here](https://buckaroo.readthedocs.io/en/latest/quickstart.html#quickstart) `buckaroo quickstart` and the following Error text appeared `buckaroo: command not found`

Please enlighten me what is the problem of my approach?

## Context

I have to see how this project works as one of my idea is to apply this idea in my project but stumbles in the first try.
## Your Environment

* Version used:
* Operating System and Architecture: Ubuntu 18.04

**Comment by atifkarim** [comment]
A silly mistake `./buckaroo quickstart` but I guess in the documentation it should use. Also, putting the installation of `buck` before `buckaroo` will be better I guess.
