### ISSUE TITLE
Issues installing buck from portable package. 

### ISSUE THREAD

**Issue by oraqlle** [LoopPerfect/buckaroo#384]
I had some issues installing buck on my system. 

## Description

I was following the portable install for buckaroo and buck on linux. Buckaroo installed fine but after downloading buck and running
```bash
chmod +x ./buck
``` 
I tried the next command 
```bash
./buck
```

## Expected Behavior

I expected it to have a similar output as running the 
```bash
./buckaroo
```
command earlier but received and error. 

## Actual Behaviour

The error is as follows:
```bash
$ ./buck
This does not appear to be the root of a Buck project. Please 'cd'
to the root of your project before running buck. If this really is
the root of your project, run
'touch .buckconfig'
and then re-run your buck command.
Traceback (most recent call last):
  File "/home/user/.local/share/warp/packages/buck/bin/buck/programs/buck.py", line 241, in <module>
  File "/home/user/.local/share/warp/packages/buck/bin/buck/programs/buck.py", line 219, in main
  File "/home/user/.local/share/warp/packages/buck/bin/buck/programs/buck_project.py", line 149, in from_current_dir
    raise NoBuckConfigFoundException()
NoBuckConfigFoundException: This does not appear to be the root of a Buck project. Please 'cd'
to the root of your project before running buck. If this really is
the root of your project, run
'touch .buckconfig'
and then re-run your buck command.
```

## Possible Fix

Is this because buck needs to be run from a project directory. I should also note that buckaroo and buck were installed within the directory ~/lib not in a project directory. I'm not sure if this is correct practice or if it should be installed locally to a project. Regards.

## Your Environment

* Version used: I used all versions listed in the current install page. Buckaroo was listed as v2.2.0 and buck at v0.3.0
* Operating System and Architecture: 
* I'm running a WSL2 instance of Ubuntu:2004.2021.825.0 (as listed on my system settings on the "app". 
* I'm using the zsh shell with p10k theme (don't know whether the theme might affect zsh configuration so I just listed it). 
* My device is a Surface Laptop 2 running Windows 11 on 64-bit architecture.

**Comment by oraqlle** [comment]
Sorry everyone. The issue was that I wasn't in a buck project directory.
